# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH

JAVA_HOME=/home/user/tools/java
export JAVA_HOME

MAVEN_HOME=/home/user/tools/maven
export MAVEN_HOME

ANT_HOME=/home/user/tools/ant
export ANT_HOME

PATH=$JAVA_HOME/bin:$ANT_HOME/bin:$MAVEN_HOME/bin:$PATH
export PATH

JAVA_OPTS="-Dfile.encoding=UTF-8 -Xms1024M -XX:MaxPermSize=800M -Xmx2048M"
export JAVA_OPTS